-- Run this in the Supabase SQL Editor (Dashboard > SQL Editor > New query)

create table if not exists temperature_readings (
    id bigint generated by default as identity primary key,
    temperature numeric(5, 2) not null,
    reading_date date not null,
    reading_time time not null,
    created_at timestamptz not null default now()
);

-- Enable Row Level Security (Supabase best practice)
alter table temperature_readings enable row level security;

-- Allow the anon key to insert readings (the simulator uses this)
create policy "Allow inserts for anon"
    on temperature_readings
    for insert
    to anon
    with check (true);

-- Allow the anon key to read readings (the web app uses this)
create policy "Allow reads for anon"
    on temperature_readings
    for select
    to anon
    using (true);

-- RLS policies control row-level access, but the anon role also needs
-- these base table-level grants or every request gets a 401/permission error.
grant usage on schema public to anon;
grant select, insert on public.temperature_readings to anon;